# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MLClassImage
                                 A QGIS plugin
 Plugin para QGIS 3.X para la clasificación de imágenes satelitales mediante algoritmos de machine learning. (SVM, KNN, RF)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-12
        copyright            : (C) 2022 by Marlon Ruiz / Universidad Distrital
        email                : mrruizf@correo.udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MLClassImage class from file MLClassImage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MLClassImage import MLClassImage
    return MLClassImage(iface)
